id: 4c96a210bbcf4c9198fe4f851e2dcd1e
name: CLR DLL Loaded Via Office Applications
path: /Advanced Threat Detection/Windows Process Monitoring
description: ''
type: standard
author: community
entity_type: workbooks
blocks:
- type: text
  code: "|Author|References|\n                 |------|--------|\n               \
    \  |Antonlovesdnb|https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16|"
- type: sql
  query: SELECT $System, $Image, $ImageLoaded FROM SYSMON-IMAGE-LOAD WHERE (($Image
    LIKE "%winword%exe%" OR $Image LIKE "%powerpnt%exe%" OR $Image LIKE "%excel%exe"
    OR $Image LIKE "%outlook%exe%") AND ($ImageLoaded LIKE "%clr%dll%")) GROUP BY  $System,
    $Image, $ImageLoaded
- type: signal
  DetectionName: CLR DLL Loaded Via Office Applications
  DetectionTactic: Execution
  DetectionTechnique: User Execution
  DetectionScore: 5
  DetectionSeverity: Medium
  DetectionConfidence: Medium
  TargetHost: $System
  raw_event_query: SELECT * FROM SYSMON-IMAGE-LOAD WHERE (($Image LIKE "%winword%exe%"
    OR $Image LIKE "%powerpnt%exe%" OR $Image LIKE "%excel%exe" OR $Image LIKE "%outlook%exe%")
    AND ($ImageLoaded LIKE "%clr%dll%")) AND $System='{TargetHost}' LIMIT 1000
cron: null
config:
  parameters: []
