id: 9afccbd897cc4a77b332d7ef0473008e
name: VPC Configuration Changes
path: /Visualization/Cloud Monitoring
description: ''
type: standard
author: DNIF
entity_type: workbooks
blocks:
- type: dql
  query: '_fetch * from event where $Stream=CLOUDTRAIL AND $Duration=1h AND $EventType=AwsApiCall
    AND  $EventName IN [DeleteVpc,CreateVpc,ModifyVpcAttribute,AcceptVpcPeeringConnection,CreateVpcPeeringConnection,DeleteVpcPeeringConnection,RejectVpcPeeringConnection]
    group count_unique  $EventName limit 10  '
- type: visual
  data:
    widget_name: VPC Configuration Changes
    chart_type: bar
    config:
      type: stacked
      key:
      - $EventName
      - $EventName
      value: count_unique
cron: null
config:
  parameters: []
