id: 08c93e60859a4950afd9db041f4170e5
name: AWS Config Disabling Channel Recorder
path: /Cloud Security/Amazon Web Services
description: ''
type: standard
author: community
entity_type: workbooks
blocks:
- type: text
  code: "|Author|References|\n                 |------|--------|\n               \
    \  |vitaliy0x1|None|"
- type: sql
  query: SELECT * FROM CONFIGURATION WHERE $Action='CONFIGURATION_CHANGED' AND ($Config='DeleteDeliveryChannel'
    OR $Config='StopConfigurationRecorder')
- type: signal
  DetectionName: AWS Config Disabling Channel/Recorder
  DetectionTactic: Defense Evasion
  DetectionTechnique: Impair Defenses
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  SuspectUser: $User
  raw_event_query: SELECT * FROM CONFIGURATION WHERE $Duration=5m AND $User='{SuspectUser}'
    LIMIT 1000
cron: null
config:
  parameters: []
