id: 96122f4420174bfc9b7c9f908784af9d
name: Azure Diagnostic Settings Deletion
path: /Cloud Security/Azure
description: ''
type: standard
author: DNIF
entity_type: workbooks
blocks:
- type: sql
  query: Select $OperationName, $User, $Status FROM AZURE WHERE $OperationName='MICROSOFT.INSIGHTS/DIAGNOSTICSETTINGS/DELETE'
    AND $Status='Succeeded' GROUP BY $OperationName, $User, $Status
- type: signal
  DetectionName: Azure Diagnostic Settings Deletion
  DetectionTactic: Defense Evasion
  DetectionTechnique: Impair Defenses
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  SuspectUser: $User
  raw_event_query: SELECT * FROM AZURE WHERE $OperationName='MICROSOFT.INSIGHTS/DIAGNOSTICSETTINGS/DELETE'
    AND $Status='Succeeded' AND $User='SuspectUser' LIMIT 1000
config: {}
