id: 58bc7573249a42b6a68257ae4987e6c6
name: Azure Application Credential Modification
path: /Cloud Security/Azure
description: ''
type: standard
author: DNIF
entity_type: workbooks
blocks:
- type: sql
  query: Select $OperationName, $User, $Status FROM AZURE WHERE $OperationName='Update
    application - Certificates and secrets management' AND $Status='Succeeded' GROUP
    BY $OperationName, $User, $Status
- type: signal
  DetectionName: Azure Application Credential Modification
  DetectionTactic: Defense Evasion
  DetectionTechnique: Use Alternate Authentication Material
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  SuspectUser: $User
  raw_event_query: SELECT * FROM AZURE WHERE $OperationName='Update application -
    Certificates and secrets management' AND $Status='Succeeded' AND $User='{SuspectUser}'
    LIMIT 1000
config: {}
